# Generated by Django 3.0 on 2020-12-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoSetting', max_length=255, verbose_name='名前')),
                ('email', models.EmailField(default='your_mail@gmail.com', max_length=255, verbose_name='メールアドレス')),
                ('github', models.CharField(blank=True, max_length=255, verbose_name='Githubアカウント')),
                ('twitter', models.CharField(blank=True, max_length=255, verbose_name='Twitterアカウント')),
                ('google_ad_html', models.TextField(blank=True, verbose_name='アドセンスHTML')),
                ('google_analytics_html', models.TextField(blank=True, verbose_name='アナリティクスHTML')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site')),
            ],
        ),
    ]
