# Generated by Django 3.0 on 2020-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoSetting', max_length=255, verbose_name='能力')),
                ('image', models.ImageField(upload_to='ability_img/', verbose_name='アイコン')),
                ('description', models.TextField(verbose_name='能力の説明')),
            ],
        ),
    ]
