# Generated by Django 3.0 on 2020-12-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name': '能力', 'verbose_name_plural': 'プログラミング能力'},
        ),
        migrations.AddField(
            model_name='sitedetail',
            name='greeting',
            field=models.TextField(default='NoSetting', verbose_name='プロフィール紹介、挨拶'),
        ),
    ]
