# Generated by Django 3.0 on 2020-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201213_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='value',
            field=models.IntegerField(default='0', verbose_name='進捗度'),
        ),
    ]
